# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickShapeStatistics
                                 A QGIS plugin
 Draw quick shapes to be used for simple zonal statistics.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by preinzi (LiberGIS)
        email                : stephan@libergis.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QuickShapeStatistics class from file QuickShapeStatistics.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quick_shape_statistics import QuickShapeStatistics
    return QuickShapeStatistics(iface)
