# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickShapeStatistics
                                 A QGIS plugin
 Draw quick shapes to be used for simple zonal statistics.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by preinzi (LiberGIS)
        email                : stephan@libergis.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, Qt
from qgis.core import QgsSettings, Qgis
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.gui import QgsRubberBand
from .quick_shape_statistics_dockwidget import QuickShapeStatisticsDockWidget
from .circle_tool import CircleTool
from .polygon_tool import PolygonTool
import os.path


class QuickShapeStatistics:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&QuickShapeStatistics')
        self.toolbar = self.iface.addToolBar(u'QuickShapeStatistics')
        self.toolbar.setObjectName(u'QuickShapeStatistics')

        self.pluginIsActive = False
        self.dockwidget = None
        self.circle_tool = None
        self.polygon_tool = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QuickShapeStatistics', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        self.rubber_band = QgsRubberBand(self.iface.mapCanvas(), Qgis.GeometryType.Polygon)
        self.rubber_band.setColor(QColor(255, 0, 0, 100))
        self.iface.currentLayerChanged.connect(self._on_layer_changed)

        circle_icon_path = os.path.join(self.plugin_dir, 'icon_circle.svg')
        polygon_icon_path = os.path.join(self.plugin_dir, 'icon_polygon.svg')

        self.circle_action = self.add_action(
            circle_icon_path, text=self.tr(u'Draw Circle for statistics'),
            callback=self.run_circle, parent=self.iface.mainWindow())
        self.polygon_action = self.add_action(
            polygon_icon_path, text=self.tr(u'Draw Polygon for statistics'),
            callback=self.run_polygon, parent=self.iface.mainWindow())

        self._set_plugin_menu_icon(os.path.join(self.plugin_dir, 'icon.svg'))

    def _set_plugin_menu_icon(self, icon_path):
        plugins_menu = self.iface.pluginMenu()
        for action in plugins_menu.actions():
            if action.text() == self.menu:
                action.setIcon(QIcon(icon_path))
                break

    def _layer_is_vector(self, layer):
        return layer is not None and layer.type() == Qgis.LayerType.Vector

    def _update_tool_layer_state(self, tool):
        valid = self._layer_is_vector(self.iface.activeLayer())
        tool.set_layer_valid(valid)
        if not valid:
            self.iface.messageBar().pushWarning(
                "QuickShapeStatistics", "Select a vector layer to use this tool.")

    def _on_layer_changed(self, layer):
        self.rubber_band.reset(Qgis.GeometryType.Polygon)
        if self.circle_tool:
            self.circle_tool.reset()
        if self.polygon_tool:
            self.polygon_tool.reset()
        active_tool = self.iface.mapCanvas().mapTool()
        if active_tool is not None and active_tool in (self.circle_tool, self.polygon_tool):
            self._update_tool_layer_state(active_tool)

    def _ensure_dockwidget(self):
        if not self.pluginIsActive:
            self.pluginIsActive = True
            if self.dockwidget is None:
                self.dockwidget = QuickShapeStatisticsDockWidget()
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockwidget)
        self.dockwidget.show()

    def run_circle(self):
        self._ensure_dockwidget()
        if self.circle_tool is None:
            self.circle_tool = CircleTool(self.iface.mapCanvas(), self.rubber_band, self._on_shape_drawn)
        self.iface.mapCanvas().setMapTool(self.circle_tool)
        self._update_tool_layer_state(self.circle_tool)

    def run_polygon(self):
        self._ensure_dockwidget()
        if self.polygon_tool is None:
            self.polygon_tool = PolygonTool(self.iface.mapCanvas(), self.rubber_band, self._on_shape_drawn)
        self.iface.mapCanvas().setMapTool(self.polygon_tool)
        self._update_tool_layer_state(self.polygon_tool)

    def _on_shape_drawn(self, geom):
        layer = self.iface.activeLayer()
        if not self._layer_is_vector(layer):
            self.iface.messageBar().pushWarning("QuickShapeStatistics", "Select a vector layer first.")
            return

        if not geom.isGeosValid():
            fixed = geom.makeValid()
            if fixed and not fixed.isEmpty() and fixed.isGeosValid():
                geom = fixed
                self.iface.messageBar().pushInfo(
                    "QuickShapeStatistics",
                    "The drawn shape had a self-intersection and was automatically corrected.")
            else:
                self.iface.messageBar().pushWarning(
                    "QuickShapeStatistics",
                    "The drawn shape is invalid and could not be corrected automatically. "
                    "Please redraw it.")
                return

        self.dockwidget.show_results(geom, layer)

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.currentLayerChanged.disconnect(self._on_layer_changed)
        self.rubber_band.reset(Qgis.GeometryType.Polygon)

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QuickShapeStatistics'),
                action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar
