# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickShapeStatisticsDockWidget
                                 A QGIS plugin
 Draw quick shapes to be used for simple zonal statistics.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by preinzi (LiberGIS)
        email                : stephan@libergis.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtGui, QtWidgets, uic
from .stats import calculate_stats
from qgis.PyQt.QtCore import pyqtSignal, QTimer

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), 'quick_shape_statistics_dockwidget_base.ui'),
    from_imports=True, import_from='quick_shape_statistics')


class QuickShapeStatisticsDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(QuickShapeStatisticsDockWidget, self).__init__(parent)
        self.setupUi(self)

        container = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(container)

        self.fieldCombo = QtWidgets.QComboBox()
        self.fieldCombo.currentTextChanged.connect(self._on_field_changed)
        layout.addWidget(self.fieldCombo)

        self.resultsTable = QtWidgets.QTableWidget()
        self.resultsTable.setColumnCount(3)
        self.resultsTable.setHorizontalHeaderLabels(["Class", "Value", "%"])
        self.resultsTable.horizontalHeader().setStretchLastSection(True)
        layout.addWidget(self.resultsTable)

        bottom_row = QtWidgets.QHBoxLayout()
        self.totalLabel = QtWidgets.QLabel("Total: -")
        bottom_row.addWidget(self.totalLabel)
        bottom_row.addStretch()
        self.copyButton = QtWidgets.QPushButton("Copy results")
        self.copyButton.clicked.connect(self._copy_to_clipboard)
        bottom_row.addWidget(self.copyButton)
        layout.addLayout(bottom_row)

        self.setWidget(container)
        self.current_aoi = None
        self.current_layer = None

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def show_results(self, aoi_geom, layer):
        self.current_aoi, self.current_layer = aoi_geom, layer
        self.fieldCombo.blockSignals(True)
        self.fieldCombo.clear()
        self.fieldCombo.addItem("(auto)")
        self.fieldCombo.addItems([f.name() for f in layer.fields()])
        self.fieldCombo.blockSignals(False)
        self._recalculate(class_field=None)

    def _on_field_changed(self, name):
        if self.current_layer:
            self._recalculate(class_field=None if name == "(auto)" else name)

    def _recalculate(self, class_field):
        result = calculate_stats(self.current_aoi, self.current_layer, class_field=class_field)
        self._populate_table(result)

    def _populate_table(self, result):
        metric = result["metric"]
        headers = {"area": "Area (m²)", "length": "Length (m)", "count": "Count"}
        show_features_col = metric != "count"

        col_headers = ["Class", headers[metric]]
        if show_features_col:
            col_headers.append("Features")
        col_headers.append("%")

        self.resultsTable.setColumnCount(len(col_headers))
        self.resultsTable.setHorizontalHeaderLabels(col_headers)
        self.resultsTable.setRowCount(0)

        total = result["total"] or 1
        colors = self._class_colors() if result["class_field"] else {}
        counts = result.get("counts", {})

        rows = sorted(result["results"].items(), key=lambda kv: kv[1], reverse=True)
        for i, (cls, value) in enumerate(rows):
            self.resultsTable.insertRow(i)
            col = 0
            item = QtWidgets.QTableWidgetItem(str(cls))
            if cls in colors:
                item.setBackground(colors[cls])
            self.resultsTable.setItem(i, col, item); col += 1

            value_text = f"{int(value)}" if metric == "count" else f"{value:,.1f}"
            self.resultsTable.setItem(i, col, QtWidgets.QTableWidgetItem(value_text)); col += 1

            if show_features_col:
                self.resultsTable.setItem(i, col, QtWidgets.QTableWidgetItem(str(counts.get(cls, 0))))
                col += 1

            self.resultsTable.setItem(i, col, QtWidgets.QTableWidgetItem(f"{100 * value / total:.1f}%"))

        if metric == "count":
            self.totalLabel.setText(f"Total: {int(result['total'])}")
        else:
            unit = "m²" if metric == "area" else "m"
            self.totalLabel.setText(f"Total: {result['total']:,.1f} {unit}")

    def _copy_to_clipboard(self):
        headers = [self.resultsTable.horizontalHeaderItem(c).text()
                   for c in range(self.resultsTable.columnCount())]
        lines = ["\t".join(headers)]
        for r in range(self.resultsTable.rowCount()):
            row = [self.resultsTable.item(r, c).text() if self.resultsTable.item(r, c) else ""
                   for c in range(self.resultsTable.columnCount())]
            lines.append("\t".join(row))
        QtWidgets.QApplication.clipboard().setText("\n".join(lines))
        self.copyButton.setText("Copied!")
        QTimer.singleShot(1200, lambda: self.copyButton.setText("Copy results"))

    def _class_colors(self):
        renderer = self.current_layer.renderer()
        colors = {}
        if hasattr(renderer, "categories"):
            for cat in renderer.categories():
                colors[cat.value()] = QtGui.QColor(cat.symbol().color())
        return colors
